---
title: "`r params$module`"  # Do NOT change this line
subtitle: "`r params$shorttitle`"  # Do NOT change this line
author: "`r params$instructor`"  # Do NOT change this line
date: "`r params$semester`"  # Do NOT change this line
params:
  module: "Data Literacy Education"  # Enter HERE the name of the presentation/course/module
  semester: "Prüfungsspecial: Hausarbeit"   # Enter HERE the date/semester/term
  shorttitle: ""  # Enter HERE a subtitle/shorttitle
  foottitle: "Data Literacy Slidecast"  # Enter HERE a title for footline
  instructor: "FOM"  # ENTER here the presentator's/instructor's name
output:
  xaringan::moon_reader:
    includes:
      after_body: insert-logo.html
    lib_dir: libs
    css: ["footer-header.css", "xafom.css"]
    nature:
      titleSlideClass: [middle, right]
      ratio: "4:3"  # Note that currently only 4:3 format is supported
      highlightLines: true
---


layout: true
  
<div class="my-header"></div>

<!-- the following lines define the header and the footer line: -->
<div class="my-footer"><span>`r params$semester`    
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
`r params$instructor` | `r params$foottitle` </span></div> 

<div class="footer-line"></div>



```{r setup, include=FALSE}
library(emojifont)
library(mosaic)

theme.fom <- theme_classic(22*1.04)
theme.fom <- theme.fom
theme_set(
  theme.fom  
)
#options(scipen=999)

data(tips, package = "reshape2")
set.seed(1896)
tips_train <- tips %>%
  sample_n(160) %>%
  select(time, size, total_bill)

tips_test <- tips %>%
  sample_n(80) %>%
  select(time, size, total_bill)

tips_anwendung <- tips_test %>%
  select(-total_bill)

```

---

## Inhalt

```{r, echo= FALSE , out.width = "15%", fig.align="center", fig.showtext=TRUE}
ggplot() + geom_emoji("woman_teacher") + theme_void()
```


Thema dieses Specials: 


- Arbeiten mit dem Hausarbeitstemplate
  

<br>

**Hinweis**: Dies ist eine Fortsetzung vom Special 6 und dem R Special 2&3.
